# Generated by Django 5.1.1 on 2024-10-03 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='Nome Padrão', max_length=100)),
                ('cpf', models.CharField(max_length=14)),
                ('lugar_onde_mora', models.CharField(default='Não especificado', max_length=100)),
                ('renda', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('situacoes_vulnerabilidade', models.TextField(default='Não especificado')),
                ('quantos_filhos', models.IntegerField(default=0)),
                ('quantas_pessoas_moram', models.IntegerField(default=1)),
                ('habilidades', models.TextField(default='Não especificado')),
                ('usuario', models.OneToOneField(default='Nome Padrão', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_responsavel', models.CharField(default='Nome Padrão', max_length=100)),
                ('nome_empresa', models.CharField(default='Nome Padrão', max_length=100)),
                ('captacao_local', models.CharField(default='valor padrão', max_length=100)),
                ('disponibilidade_residuo', models.CharField(default='Não especificado', max_length=100)),
                ('porte_fabrico', models.CharField(choices=[('pequeno', 'Pequeno'), ('medio', 'Médio'), ('grande', 'Grande')], default='pequeno', max_length=50)),
                ('tipo_residuo', models.CharField(default='Não especificado', max_length=100)),
                ('condicao_residuo', models.TextField(default='Não especificado', max_length=100)),
                ('usuario', models.OneToOneField(default='Nome Padrão', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
