# Generated by Django 5.1.1 on 2024-10-01 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('lugar_onde_mora', models.CharField(max_length=255)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacoes_de_vulnerabilidade', models.TextField(blank=True, null=True)),
                ('quantos_filhos', models.PositiveIntegerField(default=0)),
                ('quantas_pessoas_moram_com_voce', models.PositiveIntegerField(default=0)),
                ('habilidades', models.TextField(null=True)),
                ('email', models.EmailField(default='nao_informado@example.com', max_length=254)),
                ('telefone', models.CharField(default='0000000000', max_length=15)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('lugar_mora', models.CharField(max_length=255)),
                ('local_captacao', models.CharField(max_length=255)),
                ('disponibilidade_residuo', models.TextField(null=True)),
                ('descricao', models.TextField(null=True)),
                ('fabricacao_porte', models.CharField(max_length=50)),
                ('residuo_tipo', models.CharField(max_length=50)),
                ('telefone', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(default='nao_informado@example.com', max_length=254)),
                ('condicao_residuo', models.TextField(null=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
