# Generated by Django 5.1.1 on 2024-10-05 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('lugar_onde_mora', models.CharField(max_length=255)),
                ('renda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacoes_de_vulnerabilidade', models.TextField(blank=True, default='Não especificado', null=True)),
                ('quantos_filhos', models.PositiveIntegerField(default=0)),
                ('quantas_pessoas_moram_com_voce', models.PositiveIntegerField(default=0)),
                ('habilidades', models.TextField(default='Não especificado')),
            ],
        ),
        migrations.DeleteModel(
            name='Colaboradora',
        ),
    ]
