# Generated by Django 5.1.1 on 2024-10-05 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_colaborador_delete_colaboradora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresaparceira',
            name='usuario',
        ),
    ]
