# Generated by Django 5.1.1 on 2024-10-25 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_boneca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boneca',
            name='colaborador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador'),
        ),
    ]
