# Generated by Django 5.1.1 on 2024-10-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_boneca_colaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('lugar_onde_mora', models.CharField(max_length=255)),
                ('individual', models.BooleanField(default=True)),
                ('tipo_doador', models.CharField(choices=[('Financiador', 'Financiador'), ('Resíduo', 'Resíduo')], max_length=30)),
                ('data_disponibilidade', models.DateField(blank=True, null=True)),
                ('local_captacao', models.CharField(blank=True, max_length=255, null=True)),
                ('condicao_residuo', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_residuo', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
