# Generated by Django 5.1.1 on 2024-11-14 20:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_doador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boneca',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='boneca',
            name='nivel_dificuldade',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_previsao', models.DateField()),
                ('quantidade', models.PositiveIntegerField()),
                ('boneca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.boneca')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.colaborador')),
            ],
        ),
    ]
