# Generated by Django 5.1.1 on 2024-11-14 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_boneca_quantidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='colaborador',
        ),
        migrations.AddField(
            model_name='trabalho',
            name='colaboradores',
            field=models.ManyToManyField(to='app.colaborador'),
        ),
    ]
