# Generated by Django 5.1.1 on 2024-11-15 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_trabalho_colaborador_trabalho_colaboradores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boneca',
            name='colaborador',
        ),
    ]
