# Generated by Django 5.1.1 on 2024-11-25 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_boneca_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrabalhoConcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_conclusao', models.DateField(auto_now_add=True)),
                ('trabalho', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.trabalho')),
            ],
        ),
    ]
