# Generated by Django 5.1.1 on 2024-11-25 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_trabalho_data_conclusao_trabalhoconcluido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabalhoconcluido',
            name='data_conclusao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trabalhoconcluido',
            name='trabalho',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trabalho'),
        ),
    ]
