# Generated by Django 5.1.1 on 2024-11-25 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_trabalhoconcluido_data_conclusao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trabalho',
            name='data_conclusao',
        ),
        migrations.DeleteModel(
            name='TrabalhoConcluido',
        ),
    ]
