# Generated by Django 5.1.1 on 2024-11-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_trabalho_data_conclusao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('concluido', 'Concluído')], default='ativo', max_length=10),
        ),
    ]
