# Generated by Django 5.1.1 on 2024-11-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_trabalho_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
