name: Build and deploy Python app to Azure Web App - projetomanguetown-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate
      - name: Install Python dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Node.js (for Cypress)
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Ou a versão que você precisa
      - name: Install Cypress dependencies
        run: npm ci  
      - name: Run Cypress tests
        run: |
          npx cypress run --base-url=https://meusite.azurewebsites.net
  
      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

@@ -57,7 +44,7 @@
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write  

    steps:
      - name: Download artifact from build job
@@ -81,3 +68,18 @@
        with:
          app-name: 'projetomanguetown-app'
          slot-name: 'Production'
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Cypress dependencies
        run: |
          npm install
          npx cypress install
      - name: Run Cypress tests
        run: npx cypress run --env baseUrl=https://projetomanguetown-app.azurewebsites.net